runs:   
  using: "composite"
  steps:
    - name: Print output
      run: echo Installing all required dependencies..
      shell: cmd

    - uses: actions/checkout@v3.5.2
      with:
        repository: 'mtararujs/python-greetings'
        path: 'python-greetings'

    - name: Install dependencies
      working-directory: python-greetings
      run: pip install -r requirements.txt 
      shell: cmd