runs:   
  using: "composite"
  steps:
    - name: Print output
      working-directory: python-greetings
      run: |
        echo Installing all required dependencies..
        pip install -r requirements.txt 
      shell: cmd