inputs:
  port:
    description: 'Specify port for Python application to run'
    default: 7001
  environment:
    description: 'Environment for Python application'
    default: 'dev'
runs:   
  using: "composite"
  steps:
    - name: Print output
      run: echo Deployment to ${{ inputs.environment }} has started..
      shell: cmd