inputs:
  port:
    description: 'Specify port for Python application to run'
    default: 7001
  environment:
    description: 'Environment for Python application'
    default: 'dev'
runs:   
  using: "composite"
  steps:
    - name: Print output
      working-directory: python-greetings
      run: |
        echo Deployment to ${{ inputs.environment }} has started..
        pm2 delete greetings-app-${{ inputs.environment }} & set "errorlevel=0"
        pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      shell: cmd